# Generated by Django 5.1.1 on 2024-12-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('para1', models.TextField(blank=True, max_length=255, null=True)),
                ('para2', models.TextField(blank=True, max_length=255, null=True)),
                ('para3', models.TextField(blank=True, max_length=255, null=True)),
                ('para4', models.TextField(blank=True, max_length=255, null=True)),
                ('para5', models.TextField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='profile_pictures/')),
            ],
        ),
    ]
