# Generated by Django 5.1.1 on 2024-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_candidate_vote_count_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
