# Generated by Django 5.1.1 on 2024-12-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_voter_has_voted_delete_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
